name: Minimal Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Prefect test flow
      run: |
        docker-compose up -d
        sleep 10  # attendre que l'API soit prête
        docker-compose exec prefect python test_api_from_prefect.py
        docker-compose down