name: Minimal Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file from GitHub secrets
      run: |
        echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        # ajoute d'autres lignes ici si besoin

    - name: Start services with Docker Compose
      run: |
        docker compose --env-file .env up -d
        sleep 15  # attends un peu que les conteneurs démarrent

    - name: Run tests inside the Prefect container
      run: |
        docker compose exec -T prefect python test_api_from_prefect.py

    - name: Shutdown Docker Compose
      if: always()
      run: docker compose down